[package]
name = "render-blockers"
version = "0.1.0"
authors = ["Paul Sanford <me@paulsanford.net>"]
edition="2018"

[dependencies]
dot = "0.1"
goji = { git = "https://github.com/softprops/goji.git" }
structopt = "0.2"
